backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Category", name: "category", widget: "select", options: ["general","technology","entrepreneurship","digital-nomads","deign"]}
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "User Image", name: "userlogo", widget: "image" }
      - { label: "User Name", name: "username", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Second image", name: "secondimage", widget: "image" }
      - { label: "Second Text", name: "secondtext", widget: "markdown" }
      - { label: "Facebook", name: "facebook", widget: "string" }
      - { label: "LinkedIn", name: "linkedIn", widget: "string" }
      - { label: "Twitter", name: "twitter", widget: "string" }
  - name: "users" # Used in routes, e.g., /admin/collections/blog
    label: "Users" # Used in the UI
    folder: "content/users" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "User logo", name: "logo", widget: "image" }
      - { label: "User Name", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["company","individiual","startup","digital-nomads","coworking spaces","institution"," organization"]}
      - { label: "Layout", name: "layout", widget: "hidden", default: "users" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Firm Name", name: "firmname", widget: "string"}
      - { label: "OIB num", name: "oibnum", widget: "string"}
      - { label: "Adress", name: "adress", widget: "string"}
      - { label: "Facebook", name: "facebook", widget: "string" }
      - { label: "LinkedIn", name: "linkedIn", widget: "string" }
      - { label: "Twitter", name: "twitter", widget: "string" }

